[cuda]
packages = ["pytorch3d", "gsplat", "nvdiffrast", "flash-attn", "spconv", "cumm"]

[dependencies]
numpy = ">=2.0"
scipy = ">=1.11.0"
pillow = ">=10.0.0"
einops = "*"
omegaconf = "*"
easydict = ">=1.13"
loguru = ">=0.7.2"
tqdm = "*"
scikit-image = ">=0.23.1"
opencv = ">=4.9.0"
pyyaml = "*"
colorama = "*"
requests = "*"
plyfile = "*"
av = "*"

[target.linux-64.dependencies]
c-compiler = "*"

[pypi-dependencies]
timm = ">=0.9.16"
rembg = { version = "*", extras = ["cpu"] }
lpips = { git = "https://github.com/richzhang/PerceptualSimilarity.git" }
psutil = "*"
comfy-aimdo = "*"
hf_transfer = "*"
tqdm = "*"
utils3d = { git = "https://github.com/EasternJournalist/utils3d.git", rev = "9a4eb15e4021b67b12c460c7057d642626897ec8" }
pccm = ">=0.4.16"
ccimport = ">=0.4.4"
einops = "*"
transformers = "*"